name: Java CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build package (skip tests)
        run: mvn -B package -DskipTests

      - name: Fake deploy (exemplo)
        run: echo "Deploying...."