name: Notify Discord
on:
  push:
    branches: [ main ]
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged)
        uses: Ilshidur/action-discord@master
        with:
          args: '🚀 Nova alteração no repositório! Veja em: https://github.com/${{ github.repository }}'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}