name: Unit Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Run tests with Maven
        run: mvn test

      - name: Upload test reports
        uses: actions/upload-artifact@v4  
        if: always()
        with:
          name: test-reports
          path: target/surefire-reports/